# docker-compose.yml
version: "3.8"

services:
  # 1. Orchestration: Airflow
  postgres_airflow:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    networks:
      - de_net

  airflow-webserver:
    image: apache/airflow:2.8.2-python3.9
    container_name: airflow_webserver
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    depends_on:
      - postgres_airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./jobs:/opt/airflow/jobs
      - ./gx:/opt/airflow/gx
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - de_net

  airflow-scheduler:
    image: apache/airflow:2.8.2-python3.9
    container_name: airflow_scheduler
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./jobs:/opt/airflow/jobs
      - ./gx:/opt/airflow/gx
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES}
    command: scheduler
    networks:
      - de_net

  # 2. Distributed Storage: MinIO (S3-compatible)
  minio:
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    container_name: minio
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - de_net

  # 3. Distributed Compute: Spark
  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    command: >
      /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8081:8080" # Spark Master UI
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - de_net

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker ${SPARK_MASTER_URL}
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - de_net

  # 4. Query Engine: Trino
  trino-coordinator:
    image: trinodb/trino:432
    container_name: trino
    ports:
      - "8082:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    networks:
      - de_net

  # 5. Visualization: Apache Superset
  superset:
    image: amancevice/superset:2.1.0
    container_name: superset
    depends_on:
      - trino-coordinator
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_superset_secret_key_change_me
    command: >
      bash -c "pip install trino &&
               superset db upgrade &&
               superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
               superset init &&
               superset run -p 8088 --with-threads --reload --debugger"
    networks:
      - de_net

volumes:
  airflow_db_data:
  minio_data:

networks:
  de_net:
    driver: bridge